template: 'facelessuser:master-labels:labels.yml:master'

brace_expansion: true

rules:
  - labels: [infrastructure]
    patterns: ['*|{tools,requirements,.github}/**|!README.md']

  - labels: [source]
    patterns: ['soupsieve/**']

  - labels: [tests]
    patterns: ['tests/**']

  - labels: [docs]
    patterns: ['docs/**|README.md']

  - labels: [API]
    patterns: ['soupsieve/__init__.py|docs/**/api.md']

  - labels: [selectors]
    patterns: ['docs/**/selectors.md']

  - labels: [selectors, css-parsing]
    patterns: ['soupsieve/css_parser.py']

  - labels: [selectors, css-matching]
    patterns: ['soupsieve/css_match.py']

  - labels: [css-level-1]
    patterns: ['tests/test_level1/**']

  - labels: [css-level-2]
    patterns: ['tests/test_level2/**']

  - labels: [css-level-3]
    patterns: ['tests/test_level3/**']

  - labels: [css-level-4]
    patterns: ['tests/test_level4/**']

  - labels: [css-level-5]
    patterns: ['tests/test_level5/**']

  - labels: [css-custom]
    patterns: ['tests/test_extra/**']

labels:
- name: selectors
  color: subcategory
  description: Related to selector implementations.

- name: css-parsing
  color: subcategory
  description: Related to CSS parsing.

- name: css-matching
  color: subcategory
  description: Related to CSS matching.

- name: API
  color: subcategory
  description: Related to the API.

- name: css-level-1
  color: subcategory
  description: CSS level 1 selectors.

- name: css-level-2
  color: subcategory
  description: CSS level 2 selectors.

- name: css-level-3
  color: subcategory
  description: CSS level 3 selectors.

- name: css-level-4
  color: subcategory
  description: CSS level 4 selectors.

- name: css-level-5
  color: subcategory
  description: CSS level 5 selectors.

- name: css-custom
  color: subcategory
  description: CSS custom selectors.
